services:
  - type: web
    name: ngo-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    autoDeploy: true
    envVars:
      DATABASE_URL: "postgresql://<username>:<password>@<host>:5432/<dbname>"
      SECRET_KEY: "<your-secret-key>"
