"""Add document path to beneficiary

Revision ID: 08c058eb7565
Revises: bc8e4cdf876f
Create Date: 2026-03-25 23:27:02.166645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08c058eb7565'
down_revision = 'bc8e4cdf876f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('document_path')

    # ### end Alembic commands ###
