"""Add IP address to ActivityLog

Revision ID: bc8e4cdf876f
Revises: cc965275c584
Create Date: 2026-03-25 23:24:48.628793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8e4cdf876f'
down_revision = 'cc965275c584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
